/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import service.EtudiantService;
import java.util.Map;
/**
 *
 * @author ouahm
 */
public class GrapheEtudiantsParGroupe extends javax.swing.JInternalFrame {

    /**
     * Creates new form GrapheEtudiantsParGroupe
     */
    public GrapheEtudiantsParGroupe() {
       super("Répartition des étudiants par groupe", true, true, true, true); // ⚠️ Doit être en première ligne
    initComponents();
    setSize(700, 500);
    setClosable(true);
    setIconifiable(true);
    setResizable(true);
    setMaximizable(true);

    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    EtudiantService service = new EtudiantService();
    Map<String, Integer> data = service.getNombreEtudiantsParGroupe();

    for (String groupe : data.keySet()) {
        dataset.addValue(data.get(groupe), "Étudiants", groupe);
    }

    JFreeChart chart = ChartFactory.createBarChart(
            "Répartition des étudiants par groupe",
            "Groupe",
            "Nombre d'étudiants",
            dataset
    );

    ChartPanel chartPanel = new ChartPanel(chart);
    setContentPane(chartPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
