/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Utilisateur;

/**
 *
 * @author ouahm
 */
public class MDIApplication extends javax.swing.JFrame {

    private Utilisateur utilisateurConnecte;

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication(Utilisateur utilisateur) {
        initComponents();
        this.setTitle("Gestion des groupes");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.utilisateurConnecte = utilisateur;
        restreindreAcces();

    }

    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des groupes");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        grapheMenuItem = new javax.swing.JMenuBar();
        GestionMenu = new javax.swing.JMenu();
        openMenuGrpage = new javax.swing.JMenuItem();
        EtudiantMenuItem = new javax.swing.JMenuItem();
        coursMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        statistiqueMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grapheMenuItem.setBackground(new java.awt.Color(153, 51, 255));

        GestionMenu.setBackground(new java.awt.Color(153, 51, 255));
        GestionMenu.setMnemonic('f');
        GestionMenu.setText("Gestion");

        openMenuGrpage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        openMenuGrpage.setForeground(new java.awt.Color(153, 51, 255));
        openMenuGrpage.setMnemonic('o');
        openMenuGrpage.setText("Grpage");
        openMenuGrpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuGrpageActionPerformed(evt);
            }
        });
        GestionMenu.add(openMenuGrpage);

        EtudiantMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EtudiantMenuItem.setForeground(new java.awt.Color(153, 51, 255));
        EtudiantMenuItem.setMnemonic('a');
        EtudiantMenuItem.setText("Etudiant");
        EtudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtudiantMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(EtudiantMenuItem);

        coursMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        coursMenuItem.setForeground(new java.awt.Color(153, 51, 255));
        coursMenuItem.setMnemonic('x');
        coursMenuItem.setText("Cours");
        coursMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursMenuItemActionPerformed(evt);
            }
        });
        GestionMenu.add(coursMenuItem);

        grapheMenuItem.add(GestionMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Filtrer");

        contentMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contentMenuItem.setForeground(new java.awt.Color(153, 51, 255));
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Etudiant par groupe");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aboutMenuItem.setForeground(new java.awt.Color(153, 51, 255));
        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("Groupe par nom");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        grapheMenuItem.add(helpMenu);

        statistiqueMenu.setText("Statistiques");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(153, 51, 255));
        jMenuItem1.setText("Répartition des étudiants");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        statistiqueMenu.add(jMenuItem1);

        grapheMenuItem.add(statistiqueMenu);

        setJMenuBar(grapheMenuItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restreindreAcces() {

        if (utilisateurConnecte == null) {
            return;
        }

        String role = utilisateurConnecte.getRole();

        if (role.equalsIgnoreCase("ADMIN")) {
            // ✅ Admin a accès à tout
            return;
        } else if (role.equalsIgnoreCase("PROFESSEUR")) {
            // 👨‍🏫 Professeur peut gérer ses propres groupes et cours
            EtudiantMenuItem.setEnabled(false);  // ❌ Pas d'accès à la gestion des étudiants
            openMenuGrpage.setEnabled(true);     // ✅ Peut gérer ses groupes
            coursMenuItem.setEnabled(true);      // ✅ Peut gérer ses cours
            contentMenuItem.setEnabled(true);    // ✅ Peut rechercher par groupe
            aboutMenuItem.setEnabled(true);      // ✅ Peut rechercher par nom
        } else if (role.equalsIgnoreCase("ETUDIANT")) {
            // 👨‍🎓 Étudiant peut seulement voir
            GestionMenu.setEnabled(false);  // ❌ Pas d'accès à la gestion des groupes/cours
            //editMenu.setEnabled(false);      // ❌ Pas d'accès à la recherche avancée
            helpMenu.setEnabled(true);       // ✅ Peut voir les groupes et filtrer
            coursMenuItem.setEnabled(true);  // ✅ Peut voir la liste des cours
        }
    }


    private void coursMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursMenuItemActionPerformed
        CoursForm cf = new CoursForm();
        if (utilisateurConnecte.getRole().equalsIgnoreCase("ETUDIANT")) {
            cf.setReadOnlyMode(true);
        }
        desktopPane.add(cf);
        cf.setVisible(true);
    }//GEN-LAST:event_coursMenuItemActionPerformed

    private void openMenuGrpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuGrpageActionPerformed
        GrpageForm gf = new GrpageForm();
        if (utilisateurConnecte.getRole().equalsIgnoreCase("ETUDIANT")) {
            gf.setReadOnlyMode(true);
        }
        desktopPane.add(gf);
        gf.setVisible(true);
    }//GEN-LAST:event_openMenuGrpageActionPerformed

    private void EtudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtudiantMenuItemActionPerformed
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);

    }//GEN-LAST:event_EtudiantMenuItemActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        FiltrerEtudiantsParGroupe filtreFrame = new FiltrerEtudiantsParGroupe();

        desktopPane.add(filtreFrame);
        filtreFrame.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        RechercherGroupeForm rechercheFrame = new RechercherGroupeForm();

        desktopPane.add(rechercheFrame);
        rechercheFrame.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GrapheEtudiantsParGroupe graphe = new GrapheEtudiantsParGroupe();
        desktopPane.add(graphe);
        graphe.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    public javax.swing.JMenu getGestionMenu() {
        return GestionMenu;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EtudiantMenuItem;
    private javax.swing.JMenu GestionMenu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem coursMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar grapheMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem openMenuGrpage;
    private javax.swing.JMenu statistiqueMenu;
    // End of variables declaration//GEN-END:variables

}
